config/routes.rb
Rails.application.routes.draw do
  root 'roofs#index'
  resources :roofs, only: %i(index show create update)
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/roof.rb
class Roof < ApplicationRecord
  FLAT_SLOPE      = 7.89.freeze
  LOW_SLOPE       = 2.28.freeze
  MODERATE_SLOPE  = 3.29.freeze
  STEEP_SLOPE     = 5.27.freeze

  validates :name, :email, :phone, :area, :slope, presence: true

  before_save :update_estimation

  def calculate_estimation
    (area.to_i * "Roof::#{slope.upcase}_SLOPE".constantize).floor
  end

  private

  def update_estimation
    self.estimation = calculate_estimation
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/roofs_controller.rb
class RoofsController < ApplicationController
  def show
    coords   = Geocoder.search(params[:id])
    if coords.any?
      location = coords.first.coordinates
      @roof    = Roof.new(address: params[:id], latitude: location[0], longitude: location[1])
    end
  end

  def create
    @roof = Roof.new(roof_params)
    respond_to do |format|
      if @roof.save
        format.js { RoofMailer.estimation(@roof).deliver_now }
      else
        format.js
      end
    end
  end

  def update
    @roof = Roof.find(params[:id])
    respond_to do |format|
      format.js { @roof.update(quotes: params[:quotes]) }
    end
  end

  private

  def roof_params
    params.require(:roof).permit(:name, :email, :address, :phone, :latitude, :longitude, :area, :slope, :estimation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/roofs_helper.rb
module RoofsHelper
end

app/views/application/_search.html.slim
.jumbotron.text-center.roofs-search
  .container
    h1= title

    form#roofs-form.input-group.input-group-lg
      input#roofs-autocomplete.form-control aria-label='Enter Your Address Here' placeholder='Enter Your Address Here' type='text' value="#{params[:id]}" /
      span.input-group-btn
        button.btn.btn-success type='submit' Get Estimate!

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://use.fontawesome.com/14b036f48a.js"></script>

  </head>

  <body>

    <%- flash.each do |k, v| %>
        <div id="<%= k %>"><%= v %></div>
    <% end %>


    <%= yield %>

    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{GOOGLE_MAPS_API}&libraries=places&callback=roofs.init" %>
    <%= javascript_include_tag 'https://unpkg.com/leaflet.gridlayer.googlemutant@latest/Leaflet.GoogleMutant.js' %>


    <!-- Start of Async Drift Code -->
    <script>
    !function() {
      var t;
      if (t = window.driftt = window.drift = window.driftt || [], !t.init) return t.invoked ? void (window.console && console.error && console.error("Drift snippet included twice.")) : (t.invoked = !0,
      t.methods = [ "identify", "config", "track", "reset", "debug", "show", "ping", "page", "hide", "off", "on" ],
      t.factory = function(e) {
        return function() {
          var n;
          return n = Array.prototype.slice.call(arguments), n.unshift(e), t.push(n), t;
        };
      }, t.methods.forEach(function(e) {
        t[e] = t.factory(e);
      }), t.load = function(t) {
        var e, n, o, i;
        e = 3e5, i = Math.ceil(new Date() / e) * e, o = document.createElement("script"),
        o.type = "text/javascript", o.async = !0, o.crossorigin = "anonymous", o.src = "https://js.driftt.com/include/" + i + "/" + t + ".js",
        n = document.getElementsByTagName("script")[0], n.parentNode.insertBefore(o, n);
      });
    }();
    drift.SNIPPET_VERSION = '0.3.1';
    drift.load('zairespnmdfs');
    </script>
    <!-- End of Async Drift Code -->

    <!-- Start of HubSpot Embed Code -->
    <script type="text/javascript" id="hs-script-loader" async defer src="//js.hs-scripts.com/4010017.js"></script>
    <!-- End of HubSpot Embed Code -->

  </body>
</html>

app/views/roofs/_estimation.html.slim
h3= @roof.address
h5 Your roof replacement will cost approximately
h1.display-4.text-primary= number_to_currency(@roof.estimation)
p.text-secondary #{number_with_delimiter(@roof.area)} sq Ft. – #{@roof.slope.capitalize} Slope

h3.text-primary How many free quotes would you like?
.roofs-form__buttons
  = button_to '1 quote',  roof_path(@roof, quotes: 1), class: 'btn btn-outline-success', method: :put, remote: true
  = button_to '2 quotes', roof_path(@roof, quotes: 2), class: 'btn btn-outline-success', method: :put, remote: true

app/views/roofs/create.js.erb
var $form    = $('.roofs-form')
var $message = $form.find('.message')

<% if @roof.errors.any? %>
  $message.html("<div class='alert alert-danger'>Provided data seems to be invalid</div>")
<% else %>
  $form.find('.container').html("<%= escape_javascript(render('estimation', roof: @roof)) %>")
  $('#roofs-progress--estimation').addClass('bg-success')
<% end %>

app/views/roofs/index.html.slim
= render 'search', title: 'Getting a roofing estimate is free'

app/views/roofs/show.html.slim
- unless defined?(@roof)
  = render 'search', title: "Oops! The location you're looking for cannot be found!"

- else
  #roofs-progress
    .jumbotron.text-center
      .container
        .progress
          .progress-bar#roofs-progress--trace role='progressbar' style='width: 33%' Trace Roof
          .progress-bar.bg-secondary#roofs-progress--slope role='progressbar' style='width: 33%' Slope
          .progress-bar.bg-secondary#roofs-progress--estimation role='progressbar' style='width: 33%' Get Estimate

  .roofs-slides
    .roofs-trace#roofs-trace
      .roofs-trace__area#roofs-trace__area
      .roofs-trace__info#roofs-trace__info
        input#roofs-autocomplete type='text' value="#{@roof.address}"
      .roofs-trace__buttons
        button class='btn btn-primary disabled' id='roofs-trace__btn--undo' Undo
        button class='btn btn-success disabled' id='roofs-trace__btn--next' Next

    .roofs-layer.roofs-slope#roofs-slope
      .container
        h3 How steep is your roof?
        .card-group
          .card data-type='flat'
            .card-body
              h4.card-title Flat
          .card data-type='low'
            .card-body
              h4.card-title Low
          .card data-type='moderate'
            .card-body
              h4.card-title Moderate
          .card data-type='steep'
            .card-body
              h4.card-title Steep

    .roofs-layer.roofs-form
      .container
        .row.justify-content-center
          .col-5
            h3 Enter your contact info to be taken to your instant estimate.
            .message
            = bootstrap_form_for @roof, remote: true do |f|
              = f.text_field :name
              = f.email_field :email
              = f.text_field :phone
              = f.hidden_field :address
              = f.hidden_field :latitude
              = f.hidden_field :longitude
              = f.hidden_field :area
              = f.hidden_field :slope
              = f.submit 'Get Estimation', class: 'btn btn-success'

app/views/roofs/update.js.erb
$('.roofs-form__buttons').html("Thank you! <%= pluralize(params[:quotes], 'quote') %> has been requested!")